import type { Metadata } from "next";
import { Source_Sans_3 as FontSans } from "next/font/google";
import "./globals.css";


const fontSans = FontSans ({
  variable: "--font-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets :["latin"],
});

export const metadata: Metadata = {
  title: "Maheshdevai",
  description: "Generated by create next app",
  openGraph: {
    title: "Maheshdevai: AI SaaS, Built for You",
    description: "A full-stack AI-powered SaaS platform crafted with Next.js, React, Stripe, and Tailwind.",
    url: "https://maheshdevai.com", // Replace with your actual URL
    type: "website",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
